# Generated by Django 5.0.3 on 2024-03-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_aluno_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='codigo_curso',
            new_name='codigoCurso',
        ),
    ]
